spring:
  datasource:
    url: jdbc:mysql://140.143.168.25:3306/course_schedule?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 'chenzeran815600!@#'
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      continue-on-error: false